universe = vanilla
log = logs/fourkon121_$(Cluster).log

executable = fourkon121.sh
arguments = $(seed) $(fitnessFunction) $(a) $(s) $(r) $(b) $(mu) $(std)
output = outs/fourkon121_$(Cluster)_$(Process).out
error = errs/fourkon121_$(Cluster)_$(Process).err

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = slimbuild.tar.gz, New.slim, RecomMap.csv, sortedsnpdata.csv

request_cpus = 1
request_memory = 4GB
request_disk = 4GB

queue seed,fitnessFunction,a,s,r,b,mu,std from params.txt
