universe = vanilla
log = logs/4977_$(Cluster).log

executable = 4977.sh
arguments = $(seed) $(fitnessFunction) $(a) $(s) $(r) $(b) $(mu) $(std)
output = outs/4977_$(Cluster)_$(Process).out
error = errs/4977_$(Cluster)_$(Process).err

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = slimbuild.tar.gz, New.slim, sortedsnpdata.csv, mutdriftinfo.csv, RecomMap.csv

request_cpus = 1
request_memory = 2GB
request_disk = 2GB

queue seed,fitnessFunction,a,s,r,b,mu,std from params.txt
